"""Flask backend for Veo match analysis dashboard.

Serves JSON APIs for match data and provides a simple web interface for coaches.
Database: SQLite (match.db generated by pipeline)
"""

import json
import hmac
import os
import sqlite3
from pathlib import Path
from datetime import date, datetime, time
from flask import Flask, render_template, jsonify, request, send_file
from flask_cors import CORS
import io
from src.demo_season import build_demo_season
from src.clubhouse_store import (
    add_fixture,
    get_clubhouse_data,
    save_club_name,
    save_league_result,
)

app = Flask(__name__, template_folder='templates', static_folder='static')
app.jinja_env.variable_start_string = '[['
app.jinja_env.variable_end_string = ']]'
CORS(app)

DB_PATH = "output/match.db"
CLUBHOUSE_DB_PATH = Path(os.environ.get("CLUBHOUSE_DB_PATH", "output/clubhouse.db"))
app.config["CLUBHOUSE_ADMIN_KEY"] = os.environ.get("CLUBHOUSE_ADMIN_KEY", "")


def _clubhouse_write_allowed():
    configured_key = app.config.get("CLUBHOUSE_ADMIN_KEY", "")
    supplied_key = request.headers.get("X-Clubhouse-Key", "")
    return bool(configured_key) and hmac.compare_digest(configured_key, supplied_key)


def _valid_matchup(payload):
    home_team = str(payload.get("home_team", "")).strip()
    away_team = str(payload.get("away_team", "")).strip()
    if not home_team or not away_team or home_team.casefold() == away_team.casefold():
        return None
    if len(home_team) > 80 or len(away_team) > 80:
        return None
    return home_team, away_team


def ensure_database_schema():
    """Keep older analysis databases compatible with the dashboard."""
    from src.database import MatchDatabase

    MatchDatabase(DB_PATH).init()

# ============================================================================
# Database Helpers
# ============================================================================

def get_db():
    """Get database connection."""
    ensure_database_schema()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def dict_from_row(row):
    """Convert sqlite3.Row to dict."""
    return dict(row) if row else None

# ============================================================================
# API Routes
# ============================================================================

@app.route('/')
def index():
    """Serve main dashboard."""
    return render_template('club.html')

@app.route('/api/health')
def health():
    """Health check."""
    db_exists = Path(DB_PATH).exists()
    return jsonify({
        'status': 'ok',
        'database': 'ready' if db_exists else 'not_found',
        'timestamp': datetime.now().isoformat()
    })

@app.route('/api/matches')
def get_matches():
    """List all matches in database."""
    try:
        conn = get_db()
        matches = conn.execute(
            "SELECT id, label, date, duration_s FROM matches ORDER BY date DESC"
        ).fetchall()
        conn.close()
        return jsonify([dict(m) for m in matches])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/demo/season')
def get_demo_season():
    """Return a deterministic fictional season for the club interface preview."""
    return jsonify(build_demo_season())


@app.route('/api/clubhouse')
def get_clubhouse():
    data = get_clubhouse_data(CLUBHOUSE_DB_PATH)
    data['uploads_enabled'] = bool(app.config.get('CLUBHOUSE_ADMIN_KEY', ''))
    return jsonify(data)


@app.route('/api/clubhouse/verify', methods=['POST'])
def verify_clubhouse_key():
    if not app.config.get('CLUBHOUSE_ADMIN_KEY', ''):
        return jsonify({'error': 'Set CLUBHOUSE_ADMIN_KEY on the server to enable club edits and result uploads'}), 503
    if not _clubhouse_write_allowed():
        return jsonify({'error': 'That clubhouse key is not valid'}), 403
    return jsonify({'verified': True})


@app.route('/api/clubhouse/club', methods=['PUT'])
def update_club_name():
    if not _clubhouse_write_allowed():
        return jsonify({'error': 'Clubhouse write key is missing or invalid'}), 403
    payload = request.get_json(silent=True)
    club_name = str(payload.get('club_name', '')).strip() if isinstance(payload, dict) else ''
    if not club_name or len(club_name) > 80:
        return jsonify({'error': 'Enter a club name between 1 and 80 characters'}), 400
    save_club_name(CLUBHOUSE_DB_PATH, club_name)
    return jsonify(get_clubhouse_data(CLUBHOUSE_DB_PATH))


@app.route('/api/clubhouse/fixtures', methods=['POST'])
def create_club_fixture():
    if not _clubhouse_write_allowed():
        return jsonify({'error': 'Clubhouse write key is missing or invalid'}), 403
    payload = request.get_json(silent=True)
    if not isinstance(payload, dict):
        return jsonify({'error': 'Send fixture details as a JSON object'}), 400
    matchup = _valid_matchup(payload)
    venue = str(payload.get('venue', '')).strip()
    try:
        match_date = date.fromisoformat(str(payload.get('match_date', '')))
        kickoff = time.fromisoformat(str(payload.get('kickoff', ''))) if payload.get('kickoff') else None
    except ValueError:
        return jsonify({'error': 'Enter a valid date and kickoff time'}), 400
    if not matchup or not venue or len(venue) > 120:
        return jsonify({'error': 'Add two different teams and a venue (up to 120 characters)'}), 400
    if match_date < date.today():
        return jsonify({'error': 'A fixture date cannot be in the past'}), 400
    fixture = {
        'match_date': match_date.isoformat(),
        'kickoff': kickoff.strftime('%H:%M') if kickoff else '',
        'home_team': matchup[0],
        'away_team': matchup[1],
        'venue': venue,
    }
    try:
        fixture['id'] = add_fixture(CLUBHOUSE_DB_PATH, fixture)
    except sqlite3.IntegrityError:
        return jsonify({'error': 'That fixture is already on the schedule'}), 409
    return jsonify(fixture), 201


@app.route('/api/clubhouse/results', methods=['POST'])
def submit_league_result():
    if not _clubhouse_write_allowed():
        return jsonify({'error': 'Clubhouse write key is missing or invalid'}), 403
    payload = request.get_json(silent=True)
    if not isinstance(payload, dict):
        return jsonify({'error': 'Send result details as a JSON object'}), 400
    matchup = _valid_matchup(payload)
    try:
        match_date = date.fromisoformat(str(payload.get('match_date', '')))
        home_score = int(payload.get('home_score'))
        away_score = int(payload.get('away_score'))
    except (TypeError, ValueError):
        return jsonify({'error': 'Enter a valid match date and whole-number score'}), 400
    reported_by = str(payload.get('reported_by', '')).strip()
    venue = str(payload.get('venue', '')).strip()
    if not matchup or not reported_by or len(reported_by) > 80:
        return jsonify({'error': 'Add two different teams and the reporting club name'}), 400
    if not 0 <= home_score <= 50 or not 0 <= away_score <= 50:
        return jsonify({'error': 'Scores must be between 0 and 50'}), 400
    if match_date > date.today():
        return jsonify({'error': 'A result date cannot be in the future'}), 400
    result = {
        'match_date': match_date.isoformat(),
        'home_team': matchup[0],
        'away_team': matchup[1],
        'home_score': home_score,
        'away_score': away_score,
        'venue': venue[:120],
        'reported_by': reported_by,
    }
    save_league_result(CLUBHOUSE_DB_PATH, result)
    return jsonify(get_clubhouse_data(CLUBHOUSE_DB_PATH)), 201


def build_real_season():
    """Build the same report shape as the demo, using analysed matches."""
    conn = get_db()
    matches = conn.execute(
        "SELECT id, label, date, duration_s FROM matches ORDER BY date DESC, id DESC"
    ).fetchall()
    reports = {}
    for match in matches:
        match_id = match['id']
        teams = conn.execute(
            "SELECT * FROM team_stats WHERE match_id=? ORDER BY id", (match_id,)
        ).fetchall()
        players = conn.execute(
            """SELECT ps.track_id, ps.team, ps.distance_m, ps.top_speed_kmh,
                      ps.n_sprints, ps.minutes_tracked, ps.n_passes, ps.n_shots,
                      ps.n_goals, ps.possession_pct, ps.rating,
                      p.jersey_number, p.name, p.position, p.preferred_position,
                      p.photo_url,
                      a.passes_total AS passes_attempted,
                      a.passes_completed, a.pass_completion_rate,
                      a.shots AS advanced_shots, a.shots_on_target,
                      a.goals AS advanced_goals, a.dribbles, a.tackles,
                      a.interceptions, a.clearances
               FROM player_stats ps
               LEFT JOIN players p ON p.track_id = ps.track_id
               LEFT JOIN player_period_stats a
                 ON a.match_id = ps.match_id AND a.player_track_id = ps.track_id
               WHERE ps.match_id=? ORDER BY ps.team, ps.distance_m DESC""",
            (match_id,),
        ).fetchall()
        player_rows = [dict(player) for player in players]
        for player in player_rows:
            player['jersey_number'] = player['jersey_number'] if player['jersey_number'] is not None else player['track_id']
            player['name'] = player['name'] or f"Player {player['track_id']}"
            player['position'] = player['position'] or 'Unassigned'
            player['photo_url'] = player['photo_url'] or f"https://i.pravatar.cc/320?img={((int(player['track_id']) - 1) % 70) + 1}"
            player['passes_completed'] = player['passes_completed'] if player['passes_completed'] is not None else player['n_passes']
            player['passes_attempted'] = player['passes_attempted'] if player['passes_attempted'] is not None else player['n_passes']
            player['n_shots'] = player['advanced_shots'] if player['advanced_shots'] is not None else player['n_shots']
            player['goals'] = player['advanced_goals'] if player['advanced_goals'] is not None else player['n_goals']
            player['xg'] = None
            player['assists'] = None
            player['carries'] = None
            player['carry_distance_m'] = None
        team_rows = [dict(team) for team in teams]
        for team in team_rows:
            team_players = [player for player in player_rows if player['team'] == team['team']]
            attempted = sum(player['passes_attempted'] or 0 for player in team_players)
            completed = sum(player['passes_completed'] or 0 for player in team_players)
            team['pass_completion_rate'] = completed / attempted if attempted else None
            team['tackles'] = sum(player['tackles'] or 0 for player in team_players)
            team['xg'] = None
            team['assists'] = None
        goals = conn.execute(
            """SELECT timestamp_s, team, player_track_id
               FROM events WHERE match_id=? AND event_type='goal'
               ORDER BY timestamp_s""", (match_id,)
        ).fetchall()
        event_counts = conn.execute(
            "SELECT event_type, COUNT(*) AS count FROM events WHERE match_id=? GROUP BY event_type",
            (match_id,),
        ).fetchall()
        reports[match_id] = {
            'match': dict(match),
            'team_stats': team_rows,
            'players': player_rows,
            'goals': [dict(goal) for goal in goals],
            'events': {row['event_type']: row['count'] for row in event_counts},
            'data_notice': 'Stats are based on the metrics available in this analysis.',
        }
    conn.close()
    return {
        'demo': False,
        'matches': [dict(match) for match in matches],
        'reports': reports,
        'club_team': None,
        'data_notice': 'Real match analysis loaded. Some advanced metrics may be unavailable for older matches.',
    }


@app.route('/api/season')
def get_season():
    """Return demo data by default, or real analysed data when explicitly selected."""
    if request.args.get('source', 'demo').lower() != 'real':
        return jsonify(build_demo_season())
    season = build_real_season()
    if season['matches']:
        return jsonify(season)
    return jsonify(build_demo_season())


@app.route('/api/roster', methods=['GET', 'PUT'])
def roster():
    """Read or update the local club roster identity data."""
    if request.method == 'PUT':
        payload = request.get_json(silent=True)
        if not isinstance(payload, list):
            return jsonify({'error': 'Roster must be a JSON list'}), 400
        from src.database import MatchDatabase
        MatchDatabase(DB_PATH).upsert_players(payload)
    conn = get_db()
    players = conn.execute(
        """SELECT track_id, jersey_number, name, position, preferred_position,
                  photo_url, notes, active FROM players ORDER BY jersey_number, name"""
    ).fetchall()
    conn.close()
    return jsonify([dict(player) for player in players])

@app.route('/api/matches/<int:match_id>')
def get_match(match_id):
    """Get detailed match info."""
    try:
        conn = get_db()
        match = conn.execute(
            "SELECT * FROM matches WHERE id=?", (match_id,)
        ).fetchone()

        if not match:
            return jsonify({'error': 'Match not found'}), 404

        conn.close()
        return jsonify(dict(match))
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/summary')
def get_match_summary(match_id):
    """Get match summary: possession, stats, events."""
    try:
        conn = get_db()

        # Team stats
        team_stats = conn.execute(
            "SELECT team, possession_pct, total_distance_km, n_passes, n_shots, n_goals FROM team_stats WHERE match_id=?",
            (match_id,)
        ).fetchall()

        # Event counts
        event_counts = conn.execute(
            "SELECT event_type, COUNT(*) as count FROM events WHERE match_id=? GROUP BY event_type",
            (match_id,)
        ).fetchall()

        # Top performers
        top_players = conn.execute(
            """SELECT track_id, team, distance_m, top_speed_kmh AS max_speed_kmh, n_passes, n_shots
               FROM player_stats WHERE match_id=? ORDER BY distance_m DESC LIMIT 11""",
            (match_id,)
        ).fetchall()

        conn.close()

        return jsonify({
            'team_stats': [dict(t) for t in team_stats],
            'events': {row['event_type']: row['count'] for row in event_counts},
            'top_players': [dict(p) for p in top_players]
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/team-stats')
def get_team_stats(match_id):
    """Get detailed team statistics."""
    try:
        conn = get_db()
        teams = conn.execute(
            "SELECT * FROM team_stats WHERE match_id=?",
            (match_id,)
        ).fetchall()
        conn.close()
        return jsonify([dict(t) for t in teams])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/player-stats')
def get_player_stats(match_id):
    """Get all player statistics."""
    try:
        conn = get_db()
        players = conn.execute(
                        """SELECT ps.track_id, ps.team, ps.distance_m, ps.top_speed_kmh, ps.n_sprints,
                                            ps.minutes_tracked, ps.n_passes, ps.n_shots, ps.n_goals,
                                            ps.possession_pct, ps.rating,
                                            p.jersey_number, p.name, p.position, p.preferred_position, p.photo_url,
                                            a.passes_total, a.passes_completed, a.pass_completion_rate,
                                            a.dribbles, a.tackles, a.interceptions, a.clearances
                             FROM player_stats ps
                             LEFT JOIN players p ON p.track_id = ps.track_id
                             LEFT JOIN player_period_stats a
                                 ON a.match_id = ps.match_id AND a.player_track_id = ps.track_id
                             WHERE ps.match_id=? ORDER BY ps.team, ps.distance_m DESC""",
            (match_id,)
        ).fetchall()
        conn.close()
        return jsonify([dict(p) for p in players])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/possession-timeline')
def get_possession_timeline(match_id):
    """Get possession over time (5-min windows)."""
    try:
        conn = get_db()

        # Get possessions and aggregate by time windows
        possessions = conn.execute(
            "SELECT team, start_time_s, duration_s FROM possessions WHERE match_id=? ORDER BY start_time_s",
            (match_id,)
        ).fetchall()

        conn.close()

        # Bin into 5-minute windows
        windows = {}
        window_size = 300  # 5 minutes

        for poss in possessions:
            team = poss['team']
            start = poss['start_time_s']
            duration = poss['duration_s'] or 0

            window_idx = int(start / window_size)
            key = window_idx * window_size

            if key not in windows:
                windows[key] = {'team_a': 0, 'team_b': 0}

            if team == 'team_a' or team == 'Team A':
                windows[key]['team_a'] += duration
            else:
                windows[key]['team_b'] += duration

        # Convert to list with percentages
        result = []
        for key in sorted(windows.keys()):
            total = windows[key]['team_a'] + windows[key]['team_b']
            if total > 0:
                result.append({
                    'time_min': key / 60,
                    'team_a_pct': (windows[key]['team_a'] / total) * 100,
                    'team_b_pct': (windows[key]['team_b'] / total) * 100,
                })

        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/events')
def get_events(match_id):
    """Get match events (passes, shots, etc)."""
    try:
        conn = get_db()

        event_type = request.args.get('type', '')
        query = "SELECT * FROM events WHERE match_id=?"
        params = [match_id]

        if event_type:
            query += " AND event_type=?"
            params.append(event_type)

        query += " ORDER BY timestamp_s"

        events = conn.execute(query, params).fetchall()
        conn.close()

        return jsonify([dict(e) for e in events])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/pass-network')
def get_pass_network(match_id):
    """Get pass network data for both teams."""
    try:
        conn = get_db()

        # Get all passes
        passes = conn.execute(
            """SELECT team, player_track_id, location_x, location_y,
                      end_location_x, end_location_y, outcome
               FROM events WHERE match_id=? AND event_type='pass'
               ORDER BY timestamp_s""",
            (match_id,)
        ).fetchall()

        # Get player positions
        players = conn.execute(
            "SELECT track_id, team FROM player_stats WHERE match_id=?",
            (match_id,)
        ).fetchall()

        conn.close()

        return jsonify({
            'passes': [dict(p) for p in passes],
            'players': [dict(pl) for pl in players]
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/heatmap/<team>')
def get_heatmap(match_id, team):
    """Get touch/movement heatmap for a team."""
    try:
        conn = get_db()

        # Get all event locations for team
        events = conn.execute(
            """SELECT location_x, location_y FROM events
               WHERE match_id=? AND team=?
               AND location_x IS NOT NULL AND location_y IS NOT NULL""",
            (match_id, team)
        ).fetchall()

        conn.close()

        heatmap_data = [{
            'x': e['location_x'],
            'y': e['location_y']
        } for e in events]

        return jsonify(heatmap_data)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/export/pdf')
def export_pdf(match_id):
    """Export match report as PDF."""
    try:
        from reportlab.lib.pagesizes import letter, A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        from reportlab.lib import colors

        conn = get_db()

        # Get match info
        match = conn.execute("SELECT * FROM matches WHERE id=?", (match_id,)).fetchone()
        team_stats = conn.execute("SELECT * FROM team_stats WHERE match_id=?", (match_id,)).fetchall()
        player_stats = conn.execute("SELECT * FROM player_stats WHERE match_id=? ORDER BY team, distance_m DESC", (match_id,)).fetchall()

        conn.close()

        # Create PDF
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        styles = getSampleStyleSheet()

        # Title
        title = Paragraph(f"<b>Match Analysis Report</b><br/>{match['label']}", styles['Heading1'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))

        # Team Summary Table
        team_data = [['Team', 'Possession %', 'Passes', 'Shots', 'Goals', 'Distance (km)']]
        for ts in team_stats:
            team_data.append([
                ts['team'],
                f"{ts['possession_pct']:.1f}%",
                str(ts['n_passes']),
                str(ts['n_shots']),
                str(ts['n_goals']),
                f"{ts['total_distance_km']:.1f}"
            ])

        team_table = Table(team_data, colWidths=[1.5*inch, 1.2*inch, 1*inch, 1*inch, 1*inch, 1.5*inch])
        team_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(team_table)
        story.append(Spacer(1, 0.3*inch))

        # Player Stats
        story.append(Paragraph("<b>Top Players by Distance</b>", styles['Heading2']))
        story.append(Spacer(1, 0.15*inch))

        player_data = [['Track ID', 'Team', 'Distance (m)', 'Top Speed (km/h)', 'Passes', 'Shots']]
        for ps in player_stats[:15]:  # Top 15 players
            player_data.append([
                str(ps['track_id']),
                ps['team'],
                f"{ps['distance_m']:.0f}",
                f"{ps['top_speed_kmh']:.1f}",
                str(ps['n_passes']),
                str(ps['n_shots'])
            ])

        player_table = Table(player_data, colWidths=[1*inch, 1*inch, 1.2*inch, 1.5*inch, 0.8*inch, 0.8*inch])
        player_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#ecf0f1')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        story.append(player_table)

        # Build PDF
        doc.build(story)
        buffer.seek(0)

        return send_file(
            buffer,
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f"match_{match_id}_report.pdf"
        )
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# ============================================================================
# Error Handlers
# ============================================================================

@app.errorhandler(404)
def not_found(e):
    return jsonify({'error': 'Not found'}), 404

@app.errorhandler(500)
def server_error(e):
    return jsonify({'error': 'Server error', 'details': str(e)}), 500

# ============================================================================
# Run
# ============================================================================

if __name__ == '__main__':
    print("Starting Veo Match Analysis Dashboard...")
    print(f"Database: {DB_PATH}")
    print("Open browser to: http://localhost:5000")
    app.run(debug=True, host='0.0.0.0', port=5000)
