"""Flask backend for Veo match analysis dashboard.

Serves JSON APIs for match data and provides a simple web interface for coaches.
Database: SQLite (match.db generated by pipeline)
"""

import json
import sqlite3
from pathlib import Path
from datetime import datetime
from flask import Flask, render_template, jsonify, request, send_file
from flask_cors import CORS
import io

app = Flask(__name__, template_folder='templates', static_folder='static')
CORS(app)

DB_PATH = "output/match.db"

# ============================================================================
# Database Helpers
# ============================================================================

def get_db():
    """Get database connection."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def dict_from_row(row):
    """Convert sqlite3.Row to dict."""
    return dict(row) if row else None

# ============================================================================
# API Routes
# ============================================================================

@app.route('/')
def index():
    """Serve main dashboard."""
    return render_template('index.html')

@app.route('/api/health')
def health():
    """Health check."""
    db_exists = Path(DB_PATH).exists()
    return jsonify({
        'status': 'ok',
        'database': 'ready' if db_exists else 'not_found',
        'timestamp': datetime.now().isoformat()
    })

@app.route('/api/matches')
def get_matches():
    """List all matches in database."""
    try:
        conn = get_db()
        matches = conn.execute(
            "SELECT id, label, date, duration_s FROM matches ORDER BY date DESC"
        ).fetchall()
        conn.close()
        return jsonify([dict(m) for m in matches])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>')
def get_match(match_id):
    """Get detailed match info."""
    try:
        conn = get_db()
        match = conn.execute(
            "SELECT * FROM matches WHERE id=?", (match_id,)
        ).fetchone()

        if not match:
            return jsonify({'error': 'Match not found'}), 404

        conn.close()
        return jsonify(dict(match))
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/summary')
def get_match_summary(match_id):
    """Get match summary: possession, stats, events."""
    try:
        conn = get_db()

        # Team stats
        team_stats = conn.execute(
            "SELECT team, possession_pct, n_passes, n_shots, n_goals FROM team_stats WHERE match_id=?",
            (match_id,)
        ).fetchall()

        # Event counts
        event_counts = conn.execute(
            "SELECT event_type, COUNT(*) as count FROM events WHERE match_id=? GROUP BY event_type",
            (match_id,)
        ).fetchall()

        # Top performers
        top_players = conn.execute(
            """SELECT track_id, team, distance_m, max_speed_kmh, n_passes, n_shots
               FROM player_stats WHERE match_id=? ORDER BY distance_m DESC LIMIT 11""",
            (match_id,)
        ).fetchall()

        conn.close()

        return jsonify({
            'team_stats': [dict(t) for t in team_stats],
            'events': {row['event_type']: row['count'] for row in event_counts},
            'top_players': [dict(p) for p in top_players]
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/team-stats')
def get_team_stats(match_id):
    """Get detailed team statistics."""
    try:
        conn = get_db()
        teams = conn.execute(
            "SELECT * FROM team_stats WHERE match_id=?",
            (match_id,)
        ).fetchall()
        conn.close()
        return jsonify([dict(t) for t in teams])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/player-stats')
def get_player_stats(match_id):
    """Get all player statistics."""
    try:
        conn = get_db()
        players = conn.execute(
            """SELECT track_id, team, distance_m, top_speed_kmh, n_sprints,
                      minutes_tracked, n_passes, n_shots, n_goals, possession_pct, rating
               FROM player_stats WHERE match_id=? ORDER BY team, distance_m DESC""",
            (match_id,)
        ).fetchall()
        conn.close()
        return jsonify([dict(p) for p in players])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/possession-timeline')
def get_possession_timeline(match_id):
    """Get possession over time (5-min windows)."""
    try:
        conn = get_db()

        # Get possessions and aggregate by time windows
        possessions = conn.execute(
            "SELECT team, start_time_s, duration_s FROM possessions WHERE match_id=? ORDER BY start_time_s",
            (match_id,)
        ).fetchall()

        conn.close()

        # Bin into 5-minute windows
        windows = {}
        window_size = 300  # 5 minutes

        for poss in possessions:
            team = poss['team']
            start = poss['start_time_s']
            duration = poss['duration_s'] or 0

            window_idx = int(start / window_size)
            key = window_idx * window_size

            if key not in windows:
                windows[key] = {'team_a': 0, 'team_b': 0}

            if team == 'team_a' or team == 'Team A':
                windows[key]['team_a'] += duration
            else:
                windows[key]['team_b'] += duration

        # Convert to list with percentages
        result = []
        for key in sorted(windows.keys()):
            total = windows[key]['team_a'] + windows[key]['team_b']
            if total > 0:
                result.append({
                    'time_min': key / 60,
                    'team_a_pct': (windows[key]['team_a'] / total) * 100,
                    'team_b_pct': (windows[key]['team_b'] / total) * 100,
                })

        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/events')
def get_events(match_id):
    """Get match events (passes, shots, etc)."""
    try:
        conn = get_db()

        event_type = request.args.get('type', '')
        query = "SELECT * FROM events WHERE match_id=?"
        params = [match_id]

        if event_type:
            query += " AND event_type=?"
            params.append(event_type)

        query += " ORDER BY timestamp_s"

        events = conn.execute(query, params).fetchall()
        conn.close()

        return jsonify([dict(e) for e in events])
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/pass-network')
def get_pass_network(match_id):
    """Get pass network data for both teams."""
    try:
        conn = get_db()

        # Get all passes
        passes = conn.execute(
            """SELECT team, player_track_id, location_x, location_y,
                      end_location_x, end_location_y, outcome
               FROM events WHERE match_id=? AND event_type='pass'
               ORDER BY timestamp_s""",
            (match_id,)
        ).fetchall()

        # Get player positions
        players = conn.execute(
            "SELECT track_id, team FROM player_stats WHERE match_id=?",
            (match_id,)
        ).fetchall()

        conn.close()

        return jsonify({
            'passes': [dict(p) for p in passes],
            'players': [dict(pl) for pl in players]
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/heatmap/<team>')
def get_heatmap(match_id, team):
    """Get touch/movement heatmap for a team."""
    try:
        conn = get_db()

        # Get all event locations for team
        events = conn.execute(
            """SELECT location_x, location_y FROM events
               WHERE match_id=? AND team=?
               AND location_x IS NOT NULL AND location_y IS NOT NULL""",
            (match_id, team)
        ).fetchall()

        conn.close()

        heatmap_data = [{
            'x': e['location_x'],
            'y': e['location_y']
        } for e in events]

        return jsonify(heatmap_data)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/matches/<int:match_id>/export/pdf')
def export_pdf(match_id):
    """Export match report as PDF."""
    try:
        from reportlab.lib.pagesizes import letter, A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
        from reportlab.lib import colors

        conn = get_db()

        # Get match info
        match = conn.execute("SELECT * FROM matches WHERE id=?", (match_id,)).fetchone()
        team_stats = conn.execute("SELECT * FROM team_stats WHERE match_id=?", (match_id,)).fetchall()
        player_stats = conn.execute("SELECT * FROM player_stats WHERE match_id=? ORDER BY team, distance_m DESC", (match_id,)).fetchall()

        conn.close()

        # Create PDF
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
        story = []
        styles = getSampleStyleSheet()

        # Title
        title = Paragraph(f"<b>Match Analysis Report</b><br/>{match['label']}", styles['Heading1'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))

        # Team Summary Table
        team_data = [['Team', 'Possession %', 'Passes', 'Shots', 'Goals', 'Distance (km)']]
        for ts in team_stats:
            team_data.append([
                ts['team'],
                f"{ts['possession_pct']:.1f}%",
                str(ts['n_passes']),
                str(ts['n_shots']),
                str(ts['n_goals']),
                f"{ts['total_distance_km']:.1f}"
            ])

        team_table = Table(team_data, colWidths=[1.5*inch, 1.2*inch, 1*inch, 1*inch, 1*inch, 1.5*inch])
        team_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(team_table)
        story.append(Spacer(1, 0.3*inch))

        # Player Stats
        story.append(Paragraph("<b>Top Players by Distance</b>", styles['Heading2']))
        story.append(Spacer(1, 0.15*inch))

        player_data = [['Track ID', 'Team', 'Distance (m)', 'Top Speed (km/h)', 'Passes', 'Shots']]
        for ps in player_stats[:15]:  # Top 15 players
            player_data.append([
                str(ps['track_id']),
                ps['team'],
                f"{ps['distance_m']:.0f}",
                f"{ps['top_speed_kmh']:.1f}",
                str(ps['n_passes']),
                str(ps['n_shots'])
            ])

        player_table = Table(player_data, colWidths=[1*inch, 1*inch, 1.2*inch, 1.5*inch, 0.8*inch, 0.8*inch])
        player_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#ecf0f1')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        story.append(player_table)

        # Build PDF
        doc.build(story)
        buffer.seek(0)

        return send_file(
            buffer,
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f"match_{match_id}_report.pdf"
        )
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# ============================================================================
# Error Handlers
# ============================================================================

@app.errorhandler(404)
def not_found(e):
    return jsonify({'error': 'Not found'}), 404

@app.errorhandler(500)
def server_error(e):
    return jsonify({'error': 'Server error', 'details': str(e)}), 500

# ============================================================================
# Run
# ============================================================================

if __name__ == '__main__':
    print("Starting Veo Match Analysis Dashboard...")
    print(f"Database: {DB_PATH}")
    print("Open browser to: http://localhost:5000")
    app.run(debug=True, host='0.0.0.0', port=5000)
